pipeline:
  build:
    image: parallelblock/mediabuilder
    commands: make all
  publish:
    image: parallelblock/mediabuilder
    commands: 
    - echo "machine $MACHINE" > ~/.netrc
    - echo "  login $USERNAME" >> ~/.netrc
    - echo "  password $PASSWORD" >> ~/.netrc
    - make upload.all
    secrets:
    - uploadloc
    - machine
    - username
    - password
    when:
      branch: master
      event: push
