pipeline:
  build:
    image: parallelblock/mediabuilder
    commands: make all
  publish:
    image: parallelblock/mediabuilder
    commands: make upload.all
    secrets: [uploadloc]
    when:
      branch: master
      event: push
