pipeline:
  build:
    image: parallelblock/mediabuilder
    commands: make all
  publish:
    image: parallelblock/mediabuilder
    commands: 
    - bash -c "echo \"machine \${DRONE_NETRC_MACHINE}\" >> ~/.netrc"
    - bash -c "echo \"  login \${DRONE_NETRC_USERNAME}\" >> ~/.netrc"
    - bash -c "echo \"  password \${DRONE_NETRC_PASSWORD}\" >> ~/.netrc"
    - make upload.all
    secrets: [uploadloc, drone_netrc_machine, drone_netrc_username, drone_netrc_password]
    when:
      branch: master
      event: push
